// It's not a great idea to disable rules like this because the plugin can exist
// in a chain of plugins and could turn off something a wants to enable later.
//
// So this file exists to "use up" known rules, so that when new rules are added
// to the core/plugin, querying for unused ones will show the new rules.

module.exports = {
  rules: {
    ...require('./style').rules,
    ...require('./safety').rules,
    ...require('./regexp').rules,
    ...require('./whoops').rules,
    'arrow-body-style': 'off', // [ 'error', 'as-needed' ],
    'camelcase': 'off',
    'capitalized-comments': 'off',
    'class-methods-use-this': 'off',
    'complexity': 'off',
    'consistent-return': 'off',
    'consistent-this': 'off',
    'default-case': 'off',
    'func-name-matching': 'off',
    'func-names': 'off',
    'func-style': 'off',
    'function-call-argument-newline': 'off',
    'guard-for-in': 'off',
    'id-denylist': 'off',
    'id-length': 'off',
    'id-match': 'off',
    'init-declarations': 'off',
    'line-comment-position': 'off',
    'lines-around-comment': 'off',
    'logical-assignment-operators': 'off',
    'max-classes-per-file': 'off',
    'max-depth': 'off',
    'max-lines': 'off',
    'max-lines-per-function': 'off',
    'max-nested-callbacks': 'off',
    'max-params': 'off',
    'max-statements': 'off',
    'max-statements-per-line': 'off',
    'multiline-comment-style': 'off',
    'no-alert': 'off',
    'no-bitwise': 'off',
    'no-continue': 'off',
    'no-div-regex': 'off',
    'no-else-return': 'off',
    'no-empty-function': 'off',
    'no-eq-null': 'off',
    'no-implicit-coercion': 'off',
    'no-implicit-globals': 'off',
    'no-inline-comments': 'off',
    'no-invalid-this': 'off',
    'no-magic-numbers': 'off',
    'no-mixed-operators': 'off',
    'no-negated-condition': 'off',
    'no-new-native-nonconstructor': 'off',
    'no-nonoctal-decimal-escape': 'off',
    'no-param-reassign': 'off',
    'no-plusplus': 'off',
    'no-restricted-exports': 'off',
    'no-restricted-globals': 'off',
    'no-restricted-imports': 'off',
    'no-restricted-properties': 'off',
    'no-restricted-syntax': 'off',
    'no-shadow': 'off',
    'no-tabs': 'off',
    'no-ternary': 'off',
    'no-underscore-dangle': 'off',
    'no-unused-expressions': 'off',
    'no-warning-comments': 'off',
    'object-shorthand': 'off',
    'one-var-declaration-per-line': 'off',
    'operator-assignment': 'off',
    'padding-line-between-statements': 'off',
    'prefer-arrow-callback': 'off',
    'prefer-destructuring': 'off',
    'prefer-named-capture-group': 'off',
    'prefer-object-has-own': 'off', // Want it on but it requires ES2022 support
    'prefer-object-spread': 'off',
    'prefer-promise-reject-errors': 'off',
    'prefer-template': 'off',
    'require-unicode-regexp': 'off',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'sort-vars': 'off',
    'strict': 'off',
    'unicode-bom': 'off',
    'vars-on-top': 'off',
    'wrap-regex': 'off'
  }
};
