// "Whoops" rules: You probably didn't mean to do this...
module.exports = {
  rules: {
    'accessor-pairs': 'warn',
    'array-callback-return': 'error',
    'block-scoped-var': 'error',
    'constructor-super': 'error',
    'default-case-last': 'error',
    'eqeqeq': [ 'error', 'allow-null' ],
    'grouped-accessor-pairs': [ 'warn', 'anyOrder' ],
    'no-await-in-loop': 'error',
    'no-confusing-arrow': [ 'error', { allowParens: true } ],
    'no-console': [ 'warn', { allow: [ 'warn', 'error' ] } ],
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'warn',
    'no-constructor-return': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-duplicate-imports': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-label': 'error',
    'no-irregular-whitespace': 'error',
    'no-loop-func': 'error',
    'no-loss-of-precision': 'warn',
    'no-promise-executor-return': 'warn',
    'no-return-await': 'error',
    'no-template-curly-in-string': 'warn',
    'no-undefined': 'warn',
    'no-unexpected-multiline': 'error',
    'no-unmodified-loop-condition': 'error',
    'no-unreachable': 'error',
    'no-unreachable-loop': 'error',
    'no-unused-private-class-members': 'warn',
    'no-unused-vars': [ 'error', { vars: 'all', args: 'after-used', ignoreRestSiblings: true, caughtErrors: 'none' } ],
    'no-useless-backreference': 'warn',
    'no-var': 'warn',
    'prefer-const': 'warn',
    'prefer-numeric-literals': 'error',
    'radix': 'warn',
    'require-atomic-updates': 'warn',
    'require-await': 'off' // conflicts with no-return-await
  }
};
